services:
  ydb:
    image: cr.yandex/yc/yandex-docker-local-ydb@sha256:5ffb7860784d5517f60b6cf9fdf641b964395ed642d818e2b3d892259e155af9
    platform: linux/amd64
    environment:
      YDB_USE_IN_MEMORY_PDISKS: "true"
      YDB_DEFAULT_LOG_LEVEL: NOTICE
      GRPC_PORT: "2136"
      MON_PORT: "8765"
    ports:
      - "127.0.0.1:2136:2136"
      - "127.0.0.1:8765:8765"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:8765/ >/dev/null"]
      interval: 2s
      timeout: 3s
      retries: 30
